chat_app/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path("club/<uuid:profile_uuid>/", views.ChatRoomView.as_view(), name="club_chat"),
    path("team/<uuid:profile_uuid>/", views.ChatRoomView.as_view(), name="team_chat"),
    path("store/<uuid:profile_uuid>/", views.ChatRoomView.as_view(), name="store_chat"),
    path("location/<uuid:profile_uuid>/", views.ChatRoomView.as_view(), name="location_chat"),
]

clubs/urls.py
from django.urls import path
from . import views

app_name = 'clubs'

urlpatterns = [
    path("", views.ClubListView.as_view(), name="club_list"),
    path("build/<uuid:profile_uuid>/", views.ClubBuildView.as_view(), name="club_build"),
    path("delete/<uuid:profile_uuid>/", views.ClubDeleteView.as_view(), name="club_delete"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.ProfilesListView.as_view(), name='profiles-list'),
    path('build/', views.ProfileBuildView.as_view(), name='build-profile'),
    path('<uuid:profile_uuid>/', views.ProfileDetailView.as_view(), name='detail-profile'),
    path('update/<uuid:profile_uuid>/', views.ProfileUpdateView.as_view(), name='update-profile'),
    path('delete/<uuid:profile_uuid>/', views.ProfileDeleteView.as_view(), name='delete-profile'),
]

races/urls.py
from django.urls import path
from . import views

app_name = 'races'

urlpatterns = [
    path("", views.RaceListView.as_view(), name="race_list"),
    path("build/<uuid:profile_uuid>/", views.RaceBuildView.as_view(), name="race_build"),
    path("delete/<uuid:profile_uuid>/", views.RaceDeleteView.as_view(), name="race_delete"),
    path("join/<uuid:profile_uuid>/", views.RaceJoinView.as_view(), name="race_join"),
    path("locktoggle/<uuid:profile_uuid>/<uuid:race_uuid>/", views.RaceLockToggleView.as_view(), name="race_lock_toggle"),
    path("upload-lapmonitor/<uuid:race_uuid>/", views.LapMonitorUploadView.as_view(), name="lapmonitor_upload"),
    path("drag-race/<uuid:profile_uuid>/<uuid:race_uuid>/", views.RaceDragRaceView.as_view(), name="race_drag_race"),
    path("crawler-comp/<uuid:profile_uuid>/<uuid:race_uuid>/", views.RaceCrawlerCompView.as_view(), name="race_crawler_comp"),
    path("crawler-comp/run/<uuid:profile_uuid>/<uuid:race_uuid>/<uuid:racedriver_uuid>/", views.RaceCrawlerRunView.as_view(), name="race_crawler_run"),
    path("crawler-comp/finish/<uuid:profile_uuid>/<uuid:race_uuid>/", views.RaceCrawlerFinishView.as_view(), name="race_crawler_finish"),
    path("stopwatch-race/<uuid:profile_uuid>/<uuid:race_uuid>/", views.StopwatchRaceListView.as_view(), name="stopwatch_race_list"),
    path("stopwatch-race/<uuid:profile_uuid>/<uuid:race_uuid>/<uuid:racedriver_uuid>/", views.StopwatchRaceRunView.as_view(), name="stopwatch_race_run"),
    path("stopwatch-race/<uuid:profile_uuid>/<uuid:race_uuid>/finish/", views.StopwatchRaceFinishView.as_view(), name="stopwatch_race_finish"),
    path("longjump-race/<uuid:profile_uuid>/<uuid:race_uuid>/", views.LongJumpListView.as_view(), name="longjump_race_list"),
    path("longjump-race/<uuid:profile_uuid>/<uuid:race_uuid>/<uuid:racedriver_uuid>/", views.LongJumpRunView.as_view(), name="longjump_race_run"),
    path("longjump-race/<uuid:profile_uuid>/<uuid:race_uuid>/finish/", views.LongJumpFinishView.as_view(), name="longjump_race_finish"),
    path("topspeed-race/<uuid:profile_uuid>/<uuid:race_uuid>/", views.TopSpeedRaceListView.as_view(), name="topspeed_race_list"),
    path("topspeed-race/<uuid:profile_uuid>/<uuid:race_uuid>/<uuid:racedriver_uuid>/", views.TopSpeedRaceRunView.as_view(), name="topspeed_race_run"),
    path("topspeed-race/<uuid:profile_uuid>/<uuid:race_uuid>/finish/", views.TopSpeedRaceFinishView.as_view(), name="topspeed_race_finish"),
    path("judged-event/<uuid:profile_uuid>/<uuid:race_uuid>/judge/", views.JudgeJoinRaceView.as_view(), name="judged_event_judge"),
    path("judged-event/<uuid:profile_uuid>/<uuid:race_uuid>/", views.JudgedRaceListView.as_view(), name="judged_event_list"),
    path("judged-event/<uuid:profile_uuid>/<uuid:race_uuid>/<uuid:racedriver_uuid>/", views.JudgedRaceRunView.as_view(), name="judged_event_run"),
    path("judged-event/<uuid:profile_uuid>/<uuid:race_uuid>/finish/", views.JudgedRaceFinishView.as_view(), name="judged_event_finish"),
]

rekjrc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from posts import views as post_views

def custom_404(request, exception):
    return render(request, "404.html", status=404)

def custom_500(request):
    return render(request, "500.html", status=500)

urlpatterns = [
    path('', post_views.HomepageView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('builds/', include('builds.urls')),
    path('chat/', include('chat_app.urls', namespace="chat")),
    path('clubs/', include('clubs.urls')),
    path('drivers/', include('drivers.urls')),
    path('events/', include('events.urls')),
    path('humans/', include('humans.urls')),
    path('locations/', include('locations.urls')),
    path('posts/', include('posts.urls')),
    path('privacy/', include('privacy.urls')),
    path('profiles/', include('profiles.urls')),
    path('races/', include('races.urls')),
    path('sponsors/', include('sponsors.urls')),
    path('stores/', include('stores.urls')),
    path('stripe/', include('stripe_app.urls')),
    path('support/', include('support.urls')),
    path('teams/', include('teams.urls')),
    path('tracks/', include('tracks.urls')),
    path('u/', include('urls_app.urls')),
]

handler404 = 'rekjrc.urls.custom_404'
handler500 = 'rekjrc.urls.custom_500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.db.models import Count
from django.conf import settings
from rekjrc.base_models import BaseModel
from humans.models import Human
from PIL import Image

class Profile(BaseModel):
	PROFILE_TYPE_CHOICES = [
        ('DRIVER', 'Driver'),
        ('MODEL', 'Model'),
		('LOCATION', 'Location'),
		('TRACK', 'Track'),
		('RACE', 'Race'),
		('CLUB', 'Club'),
		('EVENT', 'Event'),
        ('STORE', 'Store'),
		('TEAM', 'Team'),
    ]
	human = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="human")
	profiletype = models.CharField(max_length=30, choices=PROFILE_TYPE_CHOICES)
	displayname = models.CharField(max_length=50, default='', help_text='Required')
	bio = models.TextField(blank=True, help_text='Optional')
	avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
	city = models.CharField(max_length=100, blank=True, help_text='Optional')
	state = models.CharField(max_length=100, blank=True, help_text='Optional')
	website = models.URLField(blank=True, help_text='Optional')
	chat_enabled = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.displayname} - {self.profiletype}"

	def save(self, *args, **kwargs):
		try:
			super().save(*args, **kwargs)
			if self.avatar:
				img_path = self.avatar.path
				img = Image.open(img_path)
				max_size = (200, 200)
				img.thumbnail(max_size)
				img.save(img_path, optimize=True, quality=85)
		except Exception as e:
			print("Upload failed:", e)

	@property
	def follower_count(self):
		from profiles.models import ProfileFollows
		return ProfileFollows.objects.filter(profile=self).count()

class ProfileFollows(BaseModel):
    human = models.ForeignKey(
        Human,
        on_delete=models.CASCADE,
        related_name='profile_follows')
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='followers')

    class Meta:
        unique_together = ('human', 'profile')

    def __str__(self):
        return f"{self.human.username} → {self.profile.displayname}"

profiles/forms.py
from django import forms
from .models import Profile

RACE_TYPE_CHOICES = [
    ('Lap Race',        'Lap Race'),
    ('Drag Race',       'Drag Race'),
    ('Crawler Comp',    'Crawler Comp'),
    ('Stopwatch Race',  'Stopwatch Race'),
    ('Long Jump',       'Long Jump'),
    ('Top Speed',       'Top Speed'),
    ('Judged Event',    'Judged Event')
]

class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profiletype', 'displayname', 'bio', 'avatar', 'city', 'state', 'website']
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 3, 'class': 'full-width'}),
            'displayname': forms.TextInput(attrs={'class': 'full-width'}),
            'city': forms.TextInput(attrs={'class': 'full-width'}),
            'state': forms.TextInput(attrs={'class': 'full-width'}),
            'website': forms.URLInput(attrs={'class': 'full-width'}),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        profile = self.instance
        if profile.profiletype == "race":
            print("hi")
            self.fields['race_type'] = forms.ChoiceField(
                choices=RACE_TYPE_CHOICES,
                required=True,
                label="Race Type",
                widget=forms.Select(attrs={'class': 'full-width'})
            )

class ProfileEditForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['displayname', 'bio', 'avatar', 'city', 'state', 'website']
        widgets = {
            'displayname': forms.TextInput(attrs={'class': 'full-width'}),
            'bio': forms.Textarea(attrs={'rows': 3, 'class': 'full-width'}),
            'avatar': forms.ClearableFileInput(attrs={
                'class': 'full-width',
                'accept': 'image/*'
            }),
            'city': forms.TextInput(attrs={'class': 'full-width'}),
            'state': forms.TextInput(attrs={'class': 'full-width'}),
            'website': forms.URLInput(attrs={'class': 'full-width'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        profile = self.instance
        special_types = ['CLUB', 'TEAM', 'STORE', 'LOCATION']
        if profile.profiletype in special_types:
            self.fields['chat_enabled'] = forms.BooleanField(
                required=False,
                label="Enable Chat room",
                widget=forms.CheckboxInput(attrs={'class': 'full-width'})
            )

templates/profiles/confirm_delete.html
{% extends "base.html" %}
{% block content %}
<!-- confirm_delete.html -->
<div class="middle-col">
    <h3>Delete Profile</h3>
    <p>Are you sure you want to delete your profile "{{ profile.displayname }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">
            Yes, delete my profile
        </button>
        <a href="{% url 'profiles:profiles-list' %}">Cancel</a>
    </form>
</div>
{% endblock %}

templates/profiles/profile_build.html
{% extends "base.html" %}
{% block content %}

<!-- profile_build.html -->

<div class="panel" style="text-align: center;">
    <h3>Create New Profile</h3>
    Type={{ profiletype }}
</div>

<div class="panel">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Profile</button>
    </form>
</div>

<br /><br /><br />

{% endblock %}

templates/profiles/profile_create.html
{% extends "base.html" %}
{% block content %}
<!-- profile_create.html -->
<div class="panel">
    <h2>Create Your Profile</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create Profile</button>
    </form>
</div>
{% endblock %}

templates/profiles/profile_detail.html
{% extends "base.html" %}
{% block content %}
<!-- profile_detail.html -->
<div class="panel">

  <center>
    <a href="{% url 'profiles:update-profile' profile.uuid %}">Update Profile</a><br>
    Profile Type: {{ profile.profiletype }}
    <h1>{{ profile.displayname }}</h1>

    {% if profile.avatar %}
      <img src="{{ profile.avatar.url }}" alt="{{ profile.displayname }}'s avatar" alt="Avatar" class="menu-avatar-large" />
    {% else %}
      <img src="/static/nophoto_{{ profile.profiletype }}.png" alt="{{ profile.displayname }}'s avatar" alt="Avatar" class="menu-avatar-large" />
    {% endif %}
  </center>

  {% if profile.chat_enabled %}
    <br />
    <form target="_blank" action="{% url 'chat:club_chat' profile.uuid %}" method="get">
      <button type="submit">Enter Chat Room</button>
    </form>
  {% endif %}

  {% if profile.bio %}
    <p>
      <center>
        <div style="padding: 5px; border-radius: 0.25rem; border: solid 1px white; width: 300px;">
          {{ profile.bio|linebreaksbr }}
        </div>
      </center>
    </p>
  {% endif %}

  <table align="center">
    {% if profile.city or profile.state %}
      <tr>
        <th align="left">Location:</th>
        <td>{{ profile.city }} {{ profile.state }}</td>
      </tr>
    {% endif %}

    {% if profile.website %}
      <tr>
        <th align="left">Web Site:</th>
        <td><a href="{{ profile.website }}" target="_blank">{{ profile.website }}</a></td>
      </tr>
    {% endif %}
  </table>

  {% if related_objs %}
    <center>
      {% if profile.profiletype == "MODEL" %}
        <h1>Build Attributes</h1>
      {% elif profile.profiletype == "DRIVER" %}
        <h1>Driver Attributes</h1>
      {% elif profile.profiletype == "LOCATION" %}
        <h1>Location Attributes</h1>
      {% elif profile.profiletype == "RACE" %}
        <h1><a href="{% url 'races:race_join' profile.uuid %}">Join Race</a></h1>
        <a href="/media/qrcodes/race_{{ profile.uuid }}.png" target="_blank">
          <img src="/media/qrcodes/race_{{ profile.uuid }}.png">
        </a>
      {% elif profile.profiletype == "TRACK" %}
        <h1>Track Attributes</h1>
      {% endif %}
    </center>

    {% for key, info in related_objs.items %}
      {% if info %}
        
        {% if info.locations %}
          <center>
            <h2>Club Meet Locations</h2>

            <table>
              {% for loc in info.locations %}
                <tr>
                  <td>
                    {% if loc.location.profile.avatar %}
                      <img src="{{ loc.location.profile.avatar.url }}" alt="{{ loc.location.profile.displayname }}'s avatar" class="avatar">
                    {% else %}
                      <img src="/static/nophoto_{{ loc.location.profile.profiletype }}.png" alt="{{ loc.location.profile.displayname }}'s avatar" class="avatar">
                    {% endif %}
                  </td>
                  <td>
                    <a href="{% url 'profiles:detail-profile' loc.location.profile.uuid %}">
                      {{ loc.location }}
                    </a>

                    {% if loc.location.latitude %}
                      <br>
                      <a href="https://www.google.com/maps/@{{ loc.location.latitude }},{{ loc.location.longitude }},24z" target="_blank">
                        Google Map
                      </a>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </table>
          </center>
        {% endif %}

      {% endif %}
    {% endfor %}
  {% endif %}

  {% if posts_with_images %}
    <div class="panel">
      <h3>Photos</h3>

      <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); gap: 10px;">
        {% for post in posts_with_images %}
          <a href="{{ post.image.url }}" target="_blank">
            <img src="{{ post.image.url }}" alt="Post image"
                 style="width: 100%; aspect-ratio: 1/1; object-fit: cover; border-radius: 8px; transition: transform 0.2s;">
          </a>
        {% endfor %}
      </div>
    </div>
  {% endif %}

</div>

{% endblock %}

templates/profiles/profile_detail_build.html
<!-- profile_detail_build.html -->
{% if profile.builds %}
    <div>
        <h3>{{ profile.builds.name }}</h3>
        {% if profile.builds.description %}
            <p>{{ profile.builds.description|linebreaksbr }}</p>
        {% else %}
            <p><em>No description provided.</em></p>
        {% endif %}

        {% if profile.builds.attributes.all %}
            <table>
                {% for attr in profile.builds.attributes.all %}
                    <tr>
                        <td>{{ attr.attribute_type.name }}</td>
                        <td>{{ attr.value }}</td>
                    </tr>
                {% empty %}
                    <tr><td colspan="2"><em>No attributes added yet.</em></td></tr>
                {% endfor %}
            </table>
        {% else %}
            {% comment %}<p><em>No attributes added yet.</em></p>{% endcomment %}
        {% endif %}

        {% if race.human == request.user %}
            <div>
                <a href="/builds/{{profile.id}}/update/">Update Build</a>
            </div>
        {% endif %}
    </div>
{% endif %}

templates/profiles/profile_edit.html
{% extends "base.html" %}
{% block content %}
<h2>Edit Profile</h2>
<form method="post">
    {% csrf_token %}

    <!-- ===== Profile Form ===== -->
    <fieldset>
        <legend>Profile Information</legend>
        {{ profile_form.as_p }}
    </fieldset>

    <!-- ===== Related Object Form ===== -->
    {% if related_form %}
    <fieldset>
        <legend>{{ related_type|capfirst }} Details</legend>
        {{ related_form.as_p }}
    </fieldset>
    {% endif %}

    <!-- ===== Subform Formsets as Accordions ===== -->
    <div class="accordion" id="subformsAccordion">
        {% for key, formset in view.context_data.items %}
            {% if key.endswith("_formset") %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ key }}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ key }}" aria-expanded="false" aria-controls="collapse{{ key }}">
                        {{ key|replace:"_formset"|capfirst }}
                    </button>
                </h2>
                <div id="collapse{{ key }}" class="accordion-collapse collapse" aria-labelledby="heading{{ key }}" data-bs-parent="#subformsAccordion">
                    <div class="accordion-body">
                        {{ formset.management_form }}
                        {% for form in formset %}
                            <!-- Remove alternating background classes -->
                            <div class="subform-row mb-2 p-2 border rounded">
                                {{ form.as_p }}
                                {% if form.DELETE %}
                                    <div class="form-check">
                                        {{ form.DELETE }} <label class="form-check-label">Delete</label>
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

    <button type="submit" class="btn btn-primary mt-3">Save</button>
</form>
{% endblock %}

templates/profiles/profile_header.html
<!-- profile_header.html -->
<div class="panel">
    <table>
        <tr>
            <td align="center" valign="top">
                {% if profile.avatar %}
                    <a target="_blank" href="{{ profile.avatar.url }}">
                        <img src="{{ profile.avatar.url }}" alt="Avatar" class="avatar">
                    </a>
                {% else %}
                    <img src="/static/nophoto_{{ profile.profiletype }}.png" alt="Avatar" class="avatar">
                {% endif %}
            </td>
            <td valign="top">
                <h3>
                    <a href="/profiles/{{profile.id}}/update/">
                        <u>{{ profile.displayname }}</u>
                    </a>
                </h3>
                {% if profile.city %}
                    <p>{{ profile.city }} {{ profile.state }}</p>
                {% endif %}
                {% if profile.website %}
                    <p><a href="{{ profile.website }}" target="_blank">{{ profile.website }}</a>
                {% endif %}
                {% if profile.bio %}
                    <p>{{ profile.bio|linebreaksbr }}</p>
                {% endif %}
            </td>
        </tr>
    </table>
</div>

templates/profiles/profile_not_found.html
{% extends "base.html" %}
{% block content %}
<!-- profile_not_found.html -->
<div class="middle-col">
    <h1>Profile not found</h1>
    <p>That profile may have been deleted or moved.</p>
    <a href="{% url 'homepage' %}">Go back home</a>
</div>
{% endblock %}

templates/profiles/profile_update.html
{% extends "base.html" %}
{% block content %}
<!-- profile_update.html -->
<div class="panel">
    <form action="{% url 'profiles:update-profile' profile.uuid %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <center>
            <h3>Edit {{ profile.get_profiletype_display }}</h3>
        </center>
        {{ profile_form.as_p }}
        {% if related_form %}
            {{ related_form.as_p }}
        {% endif %}
        {% include "profiles/profile_update_attributes.html" %}
        <center>
            <nowrap>
                <button type="submit" class="btn-wide">Save</button><br /><br />
                <button type="submit" class="btn-wide" onclick="self.location.href='/profiles/{{ profile.uuid }}/'">Cancel</button>
            </nowrap>
        </center>
    </form>
</div>
{% endblock %}

templates/profiles/profile_update_attributes.html
<!-- profile_update_attributes.html -->
{% for key, formset in subformsets.items %}
    <h3>{{ key|capfirst }}</h3>

    {{ formset.management_form }}

    <table class="attr-table">
        <thead>
            <tr>
                {% for field in formset.empty_form.visible_fields %}
                    {% if field.name != 'DELETE' %}
                        <th>{{ field.label }}</th>
                    {% endif %}
                {% endfor %}
                <th style="text-align:center;">Delete</th>
            </tr>
        </thead>

        <tbody id="{{ key }}-tbody">
            {% for form in formset.forms %}
                <tr>
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                        {% if field.name != 'DELETE' %}
                            <td>
                                {{ field }}

                                {% if field.help_text %}
                                    <small class="helptext">{{ field.help_text }}</small>
                                {% endif %}

                                {% for error in field.errors %}
                                    <div class="error">{{ error }}</div>
                                {% endfor %}
                            </td>
                        {% endif %}
                    {% endfor %}

                    <td class="delete-cell">
                        {% if form.DELETE %}
                            {% if form.instance.pk %}
                                <button type="button"
                                    class="delete-btn"
                                    onclick="deleteRow(this)">
                                    Delete
                                </button>
                                <input type="hidden" name="{{ form.DELETE.name }}" id="{{ form.DELETE.id_for_label }}">
                            {% else %}
                                <button type="button"
                                    class="add-btn"
                                    onclick="deleteRow(this)">
                                    Add
                                </button>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endfor %}

templates/profiles/profiles.html
{% extends "base.html" %}
{% block content %}
<!-- profiles.html -->
<div class="panel" style="text-align: center;">
    <h3>Your Profiles (<a href="/profiles/build/">New</a>)</h3>
</div>

{% for profile in profiles %}
    <div class="panel" onclick="window.location.href='/profiles/{{ profile.uuid }}/';">
        <table border="0">
            <tr>
                <td valign="top" align="center" nowrap>
                    {{ profile.get_profiletype_display }}<br />
                    {% if profile.avatar %}
                        <a target="_blank" href="{{ profile.avatar.url }}">
                            <img src="{{ profile.avatar.url }}" alt="Avatar" class="avatar">
                        </a>
                    {% else %}
                        <img src="/static/nophoto_{{ profile.profiletype }}.png" alt="Avatar" class="avatar">
                    {% endif %}
                    <a href="{% url 'profiles:update-profile' profile.uuid %}">Edit</a>
                </td>
                <td>&nbsp;&nbsp;</td>
                <td valign="top">
                    <b>{{ profile.displayname }}</b>
                    {% if profile.bio %}<p>{{ profile.bio|linebreaksbr }}</p>{% endif %}
                </td>
            </tr>
        </table>
    </div>
{% empty %}
    <p>You haven't added any profiles yet.</p>
{% endfor %}

{% endblock %}